/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author arielp
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuItemNuevoCliente = new javax.swing.JMenuItem();
        itemVerMercaderias = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuItemNuevaMercaderia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Clientes");

        jMenuItem1.setText("Ver Todos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuItemNuevoCliente.setText("Nuevo Cliente");
        menuItemNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevoClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemNuevoCliente);

        jMenuBar1.add(jMenu1);

        itemVerMercaderias.setText("Mercaderias");

        jMenuItem2.setText("Ver Mercaderias");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerMercaderiasActionPerformed(evt);
            }
        });
        itemVerMercaderias.add(jMenuItem2);

        menuItemNuevaMercaderia.setText("Nueva Mercaderia");
        menuItemNuevaMercaderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevaMercaderiaActionPerformed(evt);
            }
        });
        itemVerMercaderias.add(menuItemNuevaMercaderia);

        jMenuBar1.add(itemVerMercaderias);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.out.println("Click en Ver todos los clientes");
        ListadoClientes listadoClientes = new ListadoClientes();
        listadoClientes.setBounds(10, 10, 600, 600);
        listadoClientes.setVisible(true);

        this.add(listadoClientes);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemVerMercaderiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerMercaderiasActionPerformed

        this.listadoMercaderias = new ListadoMercaderias();
        listadoMercaderias.setBounds(10, 10, 500, 500);
        listadoMercaderias.setVisible(true);

        this.add(listadoMercaderias);

        try {
            this.nuevoCliente.setClosed(true);
        } catch (PropertyVetoException ex) {

        }
    }//GEN-LAST:event_itemVerMercaderiasActionPerformed

    private void menuItemNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevoClienteActionPerformed
        if (this.nuevoCliente == null) {
            nuevoCliente = new NuevoCliente();
            nuevoCliente.setBounds(10, 10, 500, 500);
            
        }
        nuevoCliente.setVisible(true);

        this.add(nuevoCliente);
    }//GEN-LAST:event_menuItemNuevoClienteActionPerformed

    private void menuItemNuevaMercaderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevaMercaderiaActionPerformed
        if (this.nuevoCliente == null) {
            this.nuevoCliente = new NuevoCliente();
            nuevoCliente.setBounds(10, 10, 400, 500);
            this.add(nuevoCliente);
            nuevoCliente.setVisible(true);
        }

//        NuevaMercaderia nuevaMercaderia = new NuevaMercaderia();
//        nuevaMercaderia.setBounds(10, 10, 400, 500);
//        this.add(nuevaMercaderia);
//        nuevaMercaderia.setVisible(true);

    }//GEN-LAST:event_menuItemNuevaMercaderiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itemVerMercaderias;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuItemNuevaMercaderia;
    private javax.swing.JMenuItem menuItemNuevoCliente;
    // End of variables declaration//GEN-END:variables

    private NuevoCliente nuevoCliente;
    private ListadoMercaderias listadoMercaderias;
}
